package com.cams.backend.audit;

/** Maps the PostgreSQL enum type {@code audit_action} (DATA_MODEL.md §4.6, D22). */
public enum AuditAction {
    ASSET_CREATE,
    ASSET_UPDATE,
    ASSET_DECOMMISSION,
    COMPLAINT_CREATE,
    COMPLAINT_UPDATE,
    COMPLAINT_STATUS_CHANGE,
    ASSIGNMENT_CHANGE,
    PRIORITY_CHANGE,
    COMPLAINT_VERIFY,
    COMPLAINT_CLOSE,
    COMPLAINT_REJECT,
    ACCOUNT_CREATE,
    ACCOUNT_DEACTIVATE,
    ACCOUNT_ROLE_CHANGE,
    PASSWORD_RESET,
    CATEGORY_CHANGE,
    LOCALBODY_CHANGE,
    WARD_CHANGE
}
